nodeLinker: node-modules
enableImmutableInstalls: false
enableInlineBuilds: false
enableGlobalCache: false

# Disable workspace auto-detection
# enableWorkspacePrefix: false
enableTransparentWorkspaces: false
nmSelfReferences: false 
