sonar.projectKey=hmcts_ia-ccd-definitions
sonar.organization=hmcts
sonar.projectName=IA :: CCD Definitions
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# CCD definitions repository - configuration files only, minimal analysis
sonar.sources=README.md
sonar.exclusions=definitions/**,bin/**,ccd-definition-processor/**,node_modules/**,target/**,coverage/**,test/**,tests/**,tmp/**,output/**,charts/**

# Disable coverage analysis for configuration repository
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=*
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*

