sonar.projectKey=ia-ccd-definitions
sonar.projectName=Immigration & Asylum CCD Definitions
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=definitions,bin,ccd-definition-processor/src
sonar.exclusions=**/node_modules/**,**/target/**,**/coverage/**,**/test/**,**/tests/**,**/*.test.js,**/tmp/**,**/output/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=coverage/test-report.xml
