ia-case-payments-api:
  enabled: false
ia-case-documents-api:
  enabled: false
ia-case-notifications-api:
  enabled: false
ia-home-office-integration-api:
  enabled: false
ia-bail-case-api:
  enabled: false
ia-timed-event-service:
  enabled: false
ia-hearings-api:
  enabled: false
xui-webapp:
  enabled: false
ccd:
  enabled: false
ia-aip-frontend:
  enabled: false
ccd-case-document-am-api:
  enabled: false
em-ccdorc:
  enabled: false
em-stitching:
  enabled: false
wa:
  enabled: false
servicebus:
  enabled: false
ccd-message-publisher:
  enabled: false
aac-manage-case-assignment:
  enabled: false
am-org-role-mapping-service:
  enabled: false
ia-cron-hearings-processor:
  enabled: false
redis:
  enabled: false